parameters:
    api_caller.options:
        engine:
          timeout: 10
          ssl_verifypeer: false
          useragent: "LeaseWeb API Caller"
          followlocation: true
          sslversion: 3
          fresh_connect: false